const actionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    INIT_INGREDIENT: 'INIT_INGREDIENT',
    INIT_INGREDIENT_AND_PRICE: 'INIT_INGREDIENT_AND_PRICE'
}


export default actionTypes